config/routes.rb
Rails.application.routes.draw do
  get 'home/index', to: redirect('http://localhost:3000'), as: 'home'
  root 'home#index'

  #Rutas GET para el modelo Movie para las vistas index, create y new
  get '/movie' => 'movie#index', as: 'movies'
  get 'movie/new'

  #Rutas Post para Movies
  post 'movie/create'

  #Rutas para el modelo Documentary_film para las vistas index, create y new
  get 'documentary_film/index'
  get 'documentary_film/create'
  get 'documentary_film/new'
  #Rutas para el modelo Serie para las vistas index, create y new
  get 'serie/index'
  get 'serie/create'
  get 'serie/new'
  
  # get '/mi_ruta', to: redirect('http://localhost:3000')
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/documentary_film.rb
class DocumentaryFilm < ApplicationRecord
end

app/models/movie.rb
class Movie < ApplicationRecord
    validates :name, presence: true
    validates :synopsis, presence: true
    validates :director, presence: true
end

app/models/serie.rb
class Serie < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/documentary_film_controller.rb
class DocumentaryFilmController < ApplicationController
  def index
    @documentary = Documentary.find(params[:documentary_id])
  end

  def create
    @documentary = Documentary.find(params[:documentary_id])
  end

  def new
    @documentary_film = DocumentaryFilm.new
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/movie_controller.rb
class MovieController < ApplicationController
  def index
    @movies = Movie.all
  end

  def movies_params
    params.require(:movie).permit(:name, :synopsis, :director)
  end    

  def create
    @movie = Movie.new(movies_params)
    if @movie.save
      flash[:notice] = 'La pelicula se agrego con exito'
      redirect_to :action => 'index'
      return
    else
      flash[:alert] = 'Los campos estan vacios'
      redirect_to :action => 'new'
      return
    end
  end

  def new
    @movie = Movie.new
    render :action => 'new'
    return
  end
end

app/controllers/serie_controller.rb
class SerieController < ApplicationController
  def index
    @series = Series.find(params[:series_id])
  end

  def create
    @series = Series.new(series_params)
  end

  def new
    @serie = Serie.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/documentary_film_helper.rb
module DocumentaryFilmHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/movie_helper.rb
module MovieHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/serie_helper.rb
module SerieHelper
end

app/views/documentary_film/create.html.erb
<h1>DocumentaryFilm#create</h1>
<p>Find me in app/views/documentary_film/create.html.erb</p>

app/views/documentary_film/index.html.erb
<h1>DocumentaryFilm#index</h1>
<p>Find me in app/views/documentary_film/index.html.erb</p>

app/views/documentary_film/new.html.erb
<h1>DocumentaryFilm#new</h1>
<p>Find me in app/views/documentary_film/new.html.erb</p>

app/views/home/index.html.erb
 <div class="banner">
    <p>PELICULAS</p>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Entertainment</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/movie/create.html.erb
<h1>Movie#create</h1>
<p>Find me in app/views/movie/create.html.erb</p>

app/views/movie/index.html.erb
<div class="container_index">
    <h1 style="text-align: center;">Peliculas</h1>
    <% if flash[:notice] %>
        <div class="notificacion">
            <%= flash[:notice] %>
        </div>
    <% end %>

    <%= link_to 'Agrega una nueva pelicula', movie_new_path, class: 'link' %>

    <table>
    <thead>
        <tr>
        <th>Pelicula</th>
        <th>Sinopsis</th>
        <th>Director</th>

        </tr>
    </thead>
    <tbody>
        <% @movies.sort.reverse.each do |movie| %>
        <tr>
            <td><%= movie.name %></td>
            <td><%= movie.synopsis %></td>
            <td><%= movie.director %></td>
        </tr>
        <% end %>
    </tbody>
    </table>
</div>

app/views/movie/new.html.erb
<div class="container_new">
    <h1>Peliculas</h1>

    <p>Quieres ingresar una nueva pelicula a la lista? <br>
    por favor rellena el siguiente formulario:</p>
    <% if flash[:alert] %>
        <div class="alert">
            <%= flash[:alert] %>
        </div>
    <% end %>

    <%= form_for @movie, url: movie_create_path, method: :post, html: { id: 'form' } do |f| %>
        <%= f.label "Nombre:", class: 'input' %>
        <%= f.text_field :name %><br />

        <%= f.label "Synopsis:", class: 'input' %>
        <%= f.text_area :synopsis %><br />

        <%= f.label "Director:", class: 'input' %>
        <%= f.text_field :director %><br />

        <%= f.submit :Agregar, id: 'button' %>
    <% end %>
    <br>

    <%= link_to 'Ir a Peliculas', movies_path, class: 'link', style: 'text-align: left;' %>
</div>

<script>
  document.addEventListener('DOMContentLoaded', function() {
    let formulario = document.getElementById('form');
    let botonEnvio = document.getElementById('button');

    formulario.reset();

    botonEnvio.addEventListener('click', function(event) {
      formulario.submit(); // Enviar el formulario
      location.reload(); // Recargar la página
    });
  });
</script>

app/views/serie/create.html.erb
<h1>Serie#create</h1>
<p>Find me in app/views/serie/create.html.erb</p>

app/views/serie/index.html.erb
<h1>Serie#index</h1>
<p>Find me in app/views/serie/index.html.erb</p>

app/views/serie/new.html.erb
<h1>Serie#new</h1>
<p>Find me in app/views/serie/new.html.erb</p>